//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderID { get; set; }
        public Nullable<int> userID { get; set; }
        public string orderCode { get; set; }
        public Nullable<System.DateTime> orderDay { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<int> paymentMethod { get; set; }
        public string deliveryAddress { get; set; }
        public Nullable<int> orderStatus { get; set; }
    }
}
