//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int photoID { get; set; }
        public string photoName { get; set; }
        public string photoImg { get; set; }
        public string description { get; set; }
        public Nullable<int> priceID { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> cateID { get; set; }
    }
}
