//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int priceID { get; set; }
        public Nullable<int> photoID { get; set; }
        public Nullable<int> fomatID { get; set; }
        public Nullable<decimal> price1 { get; set; }
    }
}
